export const TEST_COUNTER_INCREMENT="TEST_COUNTER_INCREMENT"
export const TEST_COUNTER_DECREMENT="TEST_COUNTER_DECREMENT"

// Auth
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SINGUP_FAILED = "USER_SINGUP_FAILED";

export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILED = "USER_SIGNIN_FAILED";

export const USER_SIGNOUT_SUCCESS = "USER_SIGNOUT_SUCCESS";